const express = require('express');
const router = express.Router();
const { protect, authorize } = require('../middleware/auth');
const User = require('../models/User');
const Lesson = require('../models/Lesson');

// In-memory report log (replace with DB model later if needed)
const reportLog = [];

const logReport = (message) => {
  reportLog.unshift({ timestamp: new Date(), message });
  if (reportLog.length > 50) reportLog.pop(); // keep last 50
};

/**
 * GET /api/growth/dashboard
 * Admin-only. Returns auto-generated growth metrics.
 */
router.get('/dashboard', protect, authorize('admin'), async (req, res) => {
  try {
    const now = new Date();
    const oneDayAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000);

    // Count daily active users (users who logged in last 24h)
    const dailyActive = await User.countDocuments({
      lastLogin: { $gte: oneDayAgo },
    });

    // Count total users
    const totalUsers = await User.countDocuments();

    // Count published lessons (proxy for chapters built)
    const publishedLessons = await Lesson.countDocuments({
      status: 'approved',
      isPublished: true,
    });

    // Count distribution channels (Telegram, TikTok, Abinet)
    // For now, hardcoded — replace with DB collection later
    const channelsActive = 0;

    // Auto-generate report messages
    const reports = [];

    if (dailyActive > 0) {
      reports.push({
        timestamp: now,
        message: `📊 Daily active users: ${dailyActive} (target: 1,000)`,
      });
    }

    if (dailyActive >= 1000) {
      reports.push({
        timestamp: now,
        message: `✅ MILESTONE: 1,000 daily users reached! Ready for AdMob.`,
      });
    }

    if (publishedLessons > 0) {
      reports.push({
        timestamp: now,
        message: `📚 Published Geez lessons: ${publishedLessons} (target: 10 chapters)`,
      });
    }

    if (publishedLessons >= 10) {
      reports.push({
        timestamp: now,
        message: `✅ MILESTONE: All 10 Geez chapters built! Move to Priority 2.`,
      });
    }

    // Auto-suggest next action based on state
    let nextFocus = '';
    if (publishedLessons < 10) {
      nextFocus = 'Build remaining Geez chapters (Priority 1)';
    } else if (channelsActive < 3) {
      nextFocus = 'Launch distribution on Telegram, TikTok, Abinet schools (Priority 2)';
    } else if (dailyActive < 1000) {
      nextFocus = 'Scale user acquisition to 1,000 daily users (Priority 3)';
    } else {
      nextFocus = 'Enable AdMob monetization (Priority 4)';
    }

    reports.push({
      timestamp: now,
      message: `🎯 Next focus: ${nextFocus}`,
    });

    // Merge with persisted log
    reports.forEach((r) => logReport(r.message));

    // Send daily email digest (only once per day)
    // This runs silently — the cron job in app.js calls this route
    if (req.query.digest === 'true') {
      sendDailyDigest({
        dailyActive,
        totalUsers,
        publishedLessons,
        channelsActive,
        nextFocus,
      }).catch((err) => console.error('Digest email error:', err));
    }

    res.json({
      success: true,
      metrics: {
        dailyActive,
        totalUsers,
        publishedLessons,
        channelsActive,
      },
      reports: reportLog.slice(0, 20),
      nextFocus,
    });
  } catch (err) {
    console.error('Growth dashboard error:', err);
    res.status(500).json({ error: err.message });
  }
});

/**
 * Helper: Send daily digest email
 */
async function sendDailyDigest({ dailyActive, totalUsers, publishedLessons, channelsActive, nextFocus }) {
  // Uses your existing email service (SendGrid/Resend/Nodemailer)
  // Adapt this to your actual email utility
  const emailService = require('../utils/email');
  if (!emailService || !emailService.send) return;

  const html = `
    <h2>📊 Quantum Tutorial — Daily Growth Report</h2>
    <ul>
      <li><strong>Daily Active Users:</strong> ${dailyActive} / 1,000</li>
      <li><strong>Total Users:</strong> ${totalUsers}</li>
      <li><strong>Published Geez Chapters:</strong> ${publishedLessons} / 10</li>
      <li><strong>Distribution Channels:</strong> ${channelsActive} / 3</li>
    </ul>
    <p style="color: #974F18;"><strong>🎯 Next focus:</strong> ${nextFocus}</p>
    <p style="font-size: 12px; color: #888;">Auto-generated by Quantum Tutorial Growth OS</p>
  `;

  await emailService.send({
    to: process.env.ADMIN_EMAIL || 'you@example.com',
    subject: `📊 Growth Report — ${dailyActive} DAU, ${publishedLessons}/10 chapters`,
    html,
  });
}

module.exports = router;